### PR TITLE
Add `OneHotEncoder` support for categoricals

### LINKED ISSUE #751: OneHotEncoder doesn't support dtype `'category'`
### Environment Details
* RDT version: 1.9.0

### Error Description
The `OneHotEncoder` transformer crashes if the dtype is `'category'` similar to the `LabelEncoder` as described in #617. Certain synthesizers -- such as `CTGANSynthesizer` and `TVAESynthesizer` -- use One Hot Encoding, so this transformer error prevents them from being able to model this type of data.

### Steps to reproduce

```python
import pandas as pd
from rdt.transformers.categorical import OneHotEncoder

# create some discrete data and store is as type 'category'
test_data = pd.DataFrame(data={
    'A': ['Yes', 'No', 'Yes', 'Maybe', 'No']
})
test_data['A'] = test_data['A'].astype('category')

# try to use one hot encoder
transformer = OneHotEncoder()
transformed_data = transformer.fit_transform(test_data, column='A')
```
Output:
```
TypeError: Cannot interpret 'CategoricalDtype(categories=['Maybe', 'No', 'Yes'], ordered=False)' as a data type
```

Stack Trace:
[stack_trace.txt](https://github.com/sdv-dev/RDT/files/13867043/stack_trace.txt)

### PR DESCRIPTION
**Pull request by fealho**
CU-86az0h0pg, Resolve #751.

### CODE REVIEW

**Comment by sdv-team** [comment]
Task linked: [CU-86az0h0pg RDT - OneHotEncoder doesn't support dtype `'category'` #751](https://app.clickup.com/t/86az0h0pg)

**Review by R-Palazzo — COMMENTED** [review]
Looks good!
In the reverse transform, should it be set back to `Category`? @npatki 
If yes, could we check this as well?

**Comment by npatki** [comment]
Yeah we always try to reverse to the same dtype that is inputted. That would be great!

**Review by pvk-developer — APPROVED** [review]

**Review by R-Palazzo — APPROVED** [review]
LGTM!

**Pull request merged**
