### PR TITLE
Allow me to use AnonymizedFaker with sdtype text columns

### LINKED ISSUE #688: Allow me to use `AnonymizedFaker` with sdtype `text` columns
### Problem Description
In RDT, the sdtype `'text'` is meant to be used for structured data such as IDs. Right now, the only allowed transformer for this is the [RegexGenerator](https://docs.sdv.dev/rdt/transformers-glossary/text-id/regexgenerator) which creates data based off a specific regex.

But in some cases, I have other requirements that the RegexGenerator cannot accommodate well. In such instances, it would be nice to use the variant of this functionality in the [bothify faker function](https://faker.readthedocs.io/en/master/providers/baseprovider.html#faker.providers.BaseProvider.bothify). Right now, I cannot do this because the `AnonymizedFaker` is deemed incompatible with `text` data.

### Expected behavior
Allow me to use the `AnonymizedFaker` with data of sdtype `text`. As the `AnonymizedFaker` includes many functions and some of them are very similar to structured text (ID).

### PR DESCRIPTION
**Pull request by amontanez24**
resolves #688 
This PR also does some cleanup in the tests to rename some and move them into classes

### CODE REVIEW

**Review by fealho — COMMENTED** [review]
@amontanez24 What test did you add to run your changes? It's hard to see since you moved the whole file to a class and GitHub marks everything as green :/

**Review by frances-h — APPROVED** [review]
LGTM

**Comment by amontanez24** [comment]
> @amontanez24 What test did you add to run your changes? It's hard to see since you moved the whole file to a class and GitHub marks everything as green :/

I think it was just this https://github.com/sdv-dev/RDT/blob/77f9a5140f41e8ec68a15da408a3f8a646777ee1/tests/integration/test_hyper_transformer.py#L1209-L1233

**Review by fealho — APPROVED** [review]
👍

**Pull request merged**
